# Generated by Django 3.2.25 on 2024-04-29 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendationproduct',
            options={},
        ),
        # error message: django.db.utils.OperationalError: (1054, "Unknown column 'custom_last_login' in 'user'")
        # aws mysql에는 이미 custom_last_login라는 필드명이 없는데, 이 필드를 last_login로 바꾸려고 하니 생긴 error
        # 따라서 models.py에서는 해당 쿼리 스크립트를 주석 처리하여 진행(2024.04.29)
        # migrations.RenameField(
        #     model_name='user',
        #     old_name='custom_last_login',
        #     new_name='last_login',
        # ),
        migrations.RemoveField(
            model_name='surveyfunction',
            name='survey_function_rank',
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
